# Generated by Django 4.2.23 on 2026-03-05 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0024_alter_userprofile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_label', models.CharField(max_length=100)),
                ('eve_title', models.CharField(help_text='Exact EVE title to match against character titles.', max_length=500)),
                ('priority', models.PositiveIntegerField(help_text='Lower = lower rank. Used for ordering.')),
                ('review_threshold_days', models.PositiveIntegerField(help_text='Days of service before a review is due.')),
                ('review_tier', models.PositiveIntegerField(choices=[(1, 'Tier 1 (R1)'), (2, 'Tier 2 (R2)'), (3, 'Tier 3 (R3)')], default=1)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='secondary', max_length=20)),
                ('default', models.BooleanField(default=False, help_text='Automatically assign this tag to new members.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='codex.taggroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAcknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(help_text='Reason for extending / acknowledging review.')),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codex_acknowledgements_given', to=settings.AUTH_USER_MODEL)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.rank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codex_review_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codex_notes_written', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codex_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('TAG_ADDED', 'Tag Added'), ('TAG_REMOVED', 'Tag Removed'), ('CHECKLIST_COMPLETED', 'Checklist Completed'), ('CHECKLIST_UNCOMPLETED', 'Checklist Uncompleted'), ('REVIEW_ACKNOWLEDGED', 'Review Acknowledged'), ('NOTE_ADDED', 'Note Added')], max_length=30)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codex_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codex_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodexConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_state', models.ForeignKey(blank=True, help_text='Only members in this state will be shown in the corporation codex.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.state')),
            ],
            options={
                'permissions': [('view_corpmember', 'Can view corporation member list'), ('manage_reviews_r1', 'Can manage Tier 1 (R1) reviews'), ('manage_reviews_r2', 'Can manage Tier 2 (R2) reviews'), ('manage_reviews_r3', 'Can manage Tier 3 (R3) reviews'), ('manage_tags', 'Can manage tags for any member')],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='codex.rank')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MemberTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codex_tags_assigned', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codex_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='MemberChecklistCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.checklistitem')),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codex_completions_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codex_checklist_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('checklist_item', 'user')},
            },
        ),
    ]
