# Generated by Django 4.2.23 on 2026-03-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='review_threshold_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days of service before a review is due. Leave blank if this rank should not be reviewed.', null=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='review_tier',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Tier 1 (R1)'), (2, 'Tier 2 (R2)'), (3, 'Tier 3 (R3)')], help_text='Review permission tier. Leave blank if this rank should not be reviewed.', null=True),
        ),
    ]
