# Generated by Django 4.2.23 on 2026-03-05 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codex', '0002_alter_rank_review_threshold_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='default',
            field=models.BooleanField(default=False, help_text='Assign this rank to new members when they join the state.'),
        ),
        migrations.AlterField(
            model_name='memberauditlog',
            name='action_type',
            field=models.CharField(choices=[('TAG_ADDED', 'Tag Added'), ('TAG_REMOVED', 'Tag Removed'), ('CHECKLIST_COMPLETED', 'Checklist Completed'), ('CHECKLIST_UNCOMPLETED', 'Checklist Uncompleted'), ('REVIEW_ACKNOWLEDGED', 'Review Acknowledged'), ('NOTE_ADDED', 'Note Added'), ('RANK_CHANGED', 'Rank Changed')], max_length=30),
        ),
        migrations.CreateModel(
            name='MemberRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codex_rank_assignments', to=settings.AUTH_USER_MODEL)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codex_rank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
