# Generated by Django 4.2.23 on 2026-03-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_rank_default_alter_memberauditlog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taggroup',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
