# Generated by Django 4.2.23 on 2026-03-08 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codex', '0005_create_member_status_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='rank_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary Rank'), ('SPECIAL', 'Special Role')], default='PRIMARY', help_text='Primary ranks are mutually exclusive; special roles can stack.', max_length=10),
        ),
        migrations.AlterField(
            model_name='memberrank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codex_ranks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='memberrank',
            unique_together={('user', 'rank')},
        ),
    ]
